name: Spotless-Checks
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
jobs:
  run-check:
    uses: martinwitt/unreusable-workflows/.github/workflows/spotless-gradle.yaml@master
    with:
      java-version: '21'
      distribution: 'oracle'
      working-dir: './'